name: Build and Release

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    types: [opened, synchronize, reopened]
    
    
jobs:
  one-creation-build:
    uses: One-Creation/.github/.github/workflows/buildAndRelease.yml@main
    with:
      projectName: ${{ github.event.repository.name }}
    secrets: inherit
