name: Octo Organization CI

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    types: [opened, synchronize, reopened]
    
    
jobs:
  call-workflow-passing-data:
    uses: onecreation/.github/workflows/build.yml@main
    with:
      projectName: ${{ github.event.repository.name }}
      secrets: inherit
