name: Deploy One-Creation Microservice

on:
  repository_dispatch:
    types:
      - deploy-event


jobs:
  call-onecreation-deploy:
    uses: One-Creation/.github/.github/workflows/deploy.yml@main
    with:
      projectName: ${{ github.event.repository.name }}
      secrets: inherit
