name: Deploy One-Creation Microservice

on:
  repository_dispatch:
    types:
      - deploy-event


jobs:
  one-creation-deploy:
    uses: One-Creation/.github/.github/workflows/deploy.yml@main
    with:
      projectName: ${{ github.event.repository.name }}
      projectAlias: #REPLACE_BY_HELM_CHART_ALIAS    
      namespace: backend       
    secrets: inherit
