name: E2E One-Creation

on:
  repository_dispatch:
    types:
      - e2e-event

jobs:
  one-creation-e2e:
    uses: One-Creation/.github/.github/workflows/e2e.yml@main
    with:
      projectName: ${{ github.event.repository.name }}
      projectAlias: #REPLACE_BY_HELM_CHART_ALIAS    
      namespace: oc${{ github.run_id }}          
    secrets: inherit
