name: E2E One-Creation

on:
 workflow_dispatch:
   inputs:
     projectName:
        required: true
        type: string
      projectAlias:
        required: true
        type: string        
      namespace:
        required: true
        type: string      
      tag:
        required: true
        type: string  
      origin_ref:
        required: true
        type: string            
      event_name:
        required: true
        type: string     
 
 repository_dispatch:
    types:
      - e2e-event

jobs:
  one-creation-e2e:
    uses: One-Creation/.github/.github/workflows/e2e.yml@main
    with:
      projectName: ${{ github.event.repository.name }}
      projectAlias: ${{ inputs.projectAlias }} 
      namespace:  ${{ inputs.namespace }}   
      tag: ${{ inputs.tag }}
      origin_ref: ${{ inputs.origin_ref }}      
      event_name: ${{ inputs.event_name }}            
    secrets: inherit
