name: Scan Secrets
on:
  push:
    branches: [ $default-branch ]
  pull_request:
    types: [opened, synchronize, reopened]
    
jobs:
  one-creation-build:
    uses: One-Creation/.github/.github/workflows/scanSecrets.yml@main
