# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    
      - name: Invoke E2E workflow and wait for conclusion
        uses: aurelien-baudet/workflow-dispatch@v2
        with:
          workflow: e2e.yml
          token: ${{ secrets.ONECREATION_PAT_TOKEN }}        
          wait-for-completion: true
          display-workflow-run-url: true
          inputs: '{ "projectName": "oc-notification", "projectAlias": "notification",  "namespace": "oc12345", "origin_ref": " ${{ github.ref }}", "tag": "123", "event_name": "${{ github.event_name }}" }'

