on:
  workflow_call:
    inputs:
      projectName:
        required: true
        type: string
      projectAlias:
        required: true
        type: string
      namespace:
        required: true
        type: string        
   
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Initialization
        id: init
        #We set the values in the output to be able to use them later
        run: |
          echo "::set-output name=origin_ref::${{ github.ref }}"
          echo "::set-output name=origin_project::${{ inputs.projectName }}"
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
    
      - name: Set up JDK 13
        uses: actions/setup-java@v3
        with:
          java-version: 13
          distribution: 'zulu'
  

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ secrets.REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          role-duration-seconds: 1200
          role-session-name: GitHubActionsOcDrmMarketplaceBuild
          
      - name: Get maven settings
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: aws s3 cp s3://com-onecreation-pipeline-resources/maven/settings.xml ~/.m2/settings.xml

      - name: Get CodeArtifact Token
        env:
          REGION: ${{ secrets.REGION }}
        run: |
          echo "CODEARTIFACT_AUTH_TOKEN=$(aws codeartifact get-authorization-token --domain onecreation --domain-owner 307126822414 --query authorizationToken --region ${{ env.REGION }} --output text)" >> $GITHUB_ENV

      - name: Restore Maven cache
        uses: skjolber/maven-cache-github-action@v1
        with:
          step: restore

      - name: Format check
        run: mvn fmt:check

      - name: Build and Test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn clean install

      - name: Quality Gate
        env:      
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PROJECT_KEY: One-Creation_${{ inputs.projectName }}
        run: mvn sonar:sonar -Dsonar.organization=one-creation -Dsonar.projectKey=${{ env.PROJECT_KEY }} -Dsonar.host.url=${{ env.SONAR_HOST_URL }} -Dsonar.login=${{ env.SONAR_TOKEN }}

      - name: Docker generation
        id: docker_gen
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          AWS_REGION: ${{ secrets.REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 cp s3://com-onecreation-pipeline-resources/maven/settings.xml ~/.m2/settings.xml
          cat  ~/.m2/settings.xml
          PROJECT_VERSION=`mvn -f ../pom.xml help:evaluate -Dexpression=project.version -q -DforceStdout`
          PROJECT_VERSION_BUILD="$PROJECT_VERSION"
          aws ecr get-login-password --region eu-central-1 | docker login 307126822414.dkr.ecr.eu-central-1.amazonaws.com -u AWS --password-stdin
          wget -O dd-java-agent.jar 'https://github.com/DataDog/dd-trace-java/releases/download/v0.97.0/dd-java-agent.jar'
          test -e ../src/main/docker/Dockerfile && cp ../src/main/docker/Dockerfile DockerFile || cp ../Dockerfile DockerFile
          docker build -t ${{ inputs.projectName}}:$PROJECT_VERSION_BUILD -f DockerFile . 
          DOCKER=307126822414.dkr.ecr.eu-central-1.amazonaws.com/one-creation/${{ inputs.projectName}}:$PROJECT_VERSION_BUILD
          docker tag ${{ inputs.projectName}}:$PROJECT_VERSION_BUILD $DOCKER
          docker push $DOCKER
          echo "::set-output name=docker_tag::$PROJECT_VERSION_BUILD"
          echo "::set-output name=docker_image::$DOCKER"
        working-directory: ./target
        
      - name: Save Maven cache
        if: always()
        uses: skjolber/maven-cache-github-action@v1
        with:
          step: save
          
#       - name: Dispatch action to run E2E
#         uses: peter-evans/repository-dispatch@v2
#         with:
#           token: ${{ secrets.ONECREATION_PAT_TOKEN }}
#           event-type: e2e-event
#           repository: One-Creation/${{ steps.init.outputs.origin_project }}
#           client-payload: '{"ref": "${{ github.ref }}", "image": "${{  steps.docker_gen.outputs.docker_image }}", "tag": "${{  steps.docker_gen.outputs.docker_tag }}", "event_name": "${{ github.event_name }}"}'

      - name: Invoke E2E workflow and wait for conclusion
        uses: aurelien-baudet/workflow-dispatch@v2
        with:
          workflow: e2e.yml
          token: ${{ secrets.ONECREATION_PAT_TOKEN }}        
          wait-for-completion: true
          display-workflow-run-url: true
          inputs: '{ "projectName": "${{ inputs.projectName }}", "projectAlias": "${{ inputs.projectAlias }}",  "namespace": "${{ inputs.namespace }}", "origin_ref": " ${{ github.ref }}", "tag": " ${{ steps.docker_gen.outputs.docker_tag }}", "event_name": "${{ github.event_name }}" }'
