on:
  workflow_call:
    inputs:
      projectName:
        required: true
        type: string
      projectAlias:
        required: true
        type: string
      namespace:
        required: true
        type: string        
   
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Initialization
        id: init
        #We set the values in the output to be able to use them later
        run: |
          echo "::set-output name=origin_ref::${{ github.ref }}"
          echo "::set-output name=origin_project::${{ inputs.projectName }}"
          echo "::set-output name=origin_event_name::${{ github.event_name  }}"
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
    
      - name: Set up JDK 13
        uses: actions/setup-java@v3
        with:
          java-version: 13
          distribution: 'zulu'
  

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ secrets.REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          role-duration-seconds: 1200
          role-session-name: GitHubActionsOcDrmMarketplaceBuild
          
      - name: Get maven settings
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: aws s3 cp s3://${{ secrets.PIPELINE_RESOURCES }}/maven/settings.xml ~/.m2/settings.xml

      - name: Get CodeArtifact Token
        env:
          REGION: ${{ secrets.REGION }}
        run: |
          echo "CODEARTIFACT_AUTH_TOKEN=$(aws codeartifact get-authorization-token --domain ${{ secrets.SONAR_DOMAIN }} --domain-owner ${{ secrets.DOMAIN_OWNER }} --query authorizationToken --region ${{ env.REGION }} --output text)" >> $GITHUB_ENV

      - name: Restore Maven cache
        uses: skjolber/maven-cache-github-action@v1
        with:
          step: restore

      - name: Format check
        # we only run if it's a pr to main branch
        if: contains(steps.init.outputs.origin_ref,'pull') && contains( steps.init.outputs.origin_event_name, 'pull_request')
        run: mvn fmt:check

      - name: Build and Test
        # we only run if it's a pr to main branch
        if: contains(steps.init.outputs.origin_ref,'pull') && contains( steps.init.outputs.origin_event_name, 'pull_request')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn clean install
 
      - name: Setup git Credentials
        if: contains(steps.init.outputs.origin_event_name, 'push')      
        uses: oleksiyrudenko/gha-git-credentials@v2.1        
        with:
          global: true
          name: 'oc-devops-github'
          email: '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'        
          token: '${{ secrets.ONECREATION_PAT_TOKEN }}'
      
      - name: Build and Close Vervsion
        # we only run if it's a pr to main branch
        if: contains(steps.init.outputs.origin_event_name, 'push')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn release:prepare -Dmaven.tests.skip=true -DautoResolveSnapshosts="all" -B -Dusername=jose-juan-lopez -Dpassword="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"
          mvn clean install -Dmaven.test.skip=true  -B -Dusername=jose-juan-lopez -Dpassword="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"
          mvn release:perform -Dmaven.tests.skip=true  -B -Dusername=jose-juan-lopez -Dpassword="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"
        
   
      - name: Quality Gate
        # we only run if it's a pr to main branch
        if: contains(steps.init.outputs.origin_ref,'pull') && contains( steps.init.outputs.origin_event_name, 'pull_request')
        env:      
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PROJECT_KEY: One-Creation_${{ inputs.projectName }}
        run: mvn sonar:sonar -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }} -Dsonar.projectKey=${{ env.PROJECT_KEY }} -Dsonar.host.url=${{ env.SONAR_HOST_URL }} -Dsonar.login=${{ env.SONAR_TOKEN }}

      - name: Docker generation
        # we only run if it's a pr to main branch
        id: docker_gen
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          AWS_REGION: ${{ secrets.REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |      
          PROJECT_VERSION=`mvn -f ../pom.xml help:evaluate -Dexpression=project.version -q -DforceStdout`
          PROJECT_VERSION_BUILD="$PROJECT_VERSION"
          aws ecr get-login-password --region ${{ secrets.REGION }}| docker login ${{ secrets.DOCKER_REPO }} -u AWS --password-stdin
          wget -O dd-java-agent.jar 'https://github.com/DataDog/dd-trace-java/releases/download/v0.97.0/dd-java-agent.jar'
          test -e ../src/main/docker/Dockerfile && cp ../src/main/docker/Dockerfile DockerFile || cp ../Dockerfile DockerFile
          docker build -t ${{ inputs.projectName}}:$PROJECT_VERSION_BUILD -f DockerFile . 
          DOCKER=${{ secrets.DOCKER_REPO }}/${{ secrets.DOCKER_ORGANIZATION }}/${{ inputs.projectName}}:$PROJECT_VERSION_BUILD
          docker tag ${{ inputs.projectName}}:$PROJECT_VERSION_BUILD $DOCKER
          docker push $DOCKER
          echo "::set-output name=docker_tag::$PROJECT_VERSION_BUILD"
          echo "::set-output name=docker_image::$DOCKER"
        working-directory: ./target
   
      - name: Save Maven cache
        if: always()
        uses: skjolber/maven-cache-github-action@v1
        with:
          step: save
          
      - name: Invoke E2E workflow and wait for conclusion
        uses: aurelien-baudet/workflow-dispatch@v2
        with:
          workflow: e2e.yml
          token: ${{ secrets.ONECREATION_PAT_TOKEN }}        
          wait-for-completion: true
          display-workflow-run-url: true
          ref: develop
          inputs: '{ "projectName": "${{ inputs.projectName }}", "projectAlias": "${{ inputs.projectAlias }}",  "namespace": "${{ inputs.namespace }}", "origin_ref": " ${{ github.ref }}", "tag": "${{ steps.docker_gen.outputs.docker_tag }}", "event_name": "${{ github.event_name }}" }'
