name: Scan Secrets
on:
  workflow_call
  
jobs:
  TruffleHog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3        
        with:
          ref: 'develop'
          fetch-depth: 0  
   
      - name: Find first and last commits of Branch
        id: commits
        run: |
          git checkout ${{ github.head_ref }}
          git pull
          git fetch
          echo "::set-output name=last::$(git log  develop..${{ github.head_ref }} | cut -d' ' -f 2 | head -n 1)"
          echo "::set-output name=first::$(git log  develop..${{ github.head_ref }} | cut -d' ' -f 2 | tail -n 5 | head -n 1)"
   
      - name: Validate if current PR can have exposed secrets
        uses: trufflesecurity/trufflehog@v3.4.3
        with:
          path: ./
          base: ${{ steps.commits.outputs.first }}
          head: ${{ github.head_ref }}
          args: "--max-depth=1"
        
      - name: Message
        if: failure()
        run: |
          echo "YOUR COMMIT IS NOT SECURE!!! FOLLOW THE STEPS BELOW AND REMOVE IT FROM GIT" >> $GITHUB_STEP_SUMMARY
          echo " https://fedingo.com/how-to-delete-commits-in-git/ " >> $GITHUB_STEP_SUMMARY
          echo "YOUR COMMIT IS NOT SECURE!!! FOLLOW THE STEPS BELOW AND REMOVE IT FROM GIT"
          echo " https://fedingo.com/how-to-delete-commits-in-git/ "
          
