name: Scan Secrets
on:
  workflow_call
  
jobs:
  TruffleHog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  
   
      - name: Validate if current PR can have exposed secrets
        uses: trufflesecurity/trufflehog@v3.4.3
        with:
          path: ./
          base: ${{ github.head_ref }}
          head: ${{ github.head_ref }}
