name: Scan Secrets
on:
  workflow_call
  
jobs:
  TruffleHog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3        
        with:
          ref: 'develop'
          fetch-depth: 0  
   
      - name: Find first and last commits of Branch
        id: commits
        run: |
          git checkout ${{ github.head_ref }}
          git pull
          git fetch
          echo "::set-output name=last::$(git log  develop..${{ github.head_ref }} | cut -d' ' -f 2 | head -n 1)"
          echo "::set-output name=first::$(git log  develop..${{ github.head_ref }} | cut -d' ' -f 2 | tail -n 5 | head -n 1)"
   
      - name: Validate if current PR can have exposed secrets
        uses: trufflesecurity/trufflehog@v3.4.3
        with:
          path: ./
          base: ${{ steps.commits.outputs.first }}
          head: ${{ github.head_ref }}
        
      - name: Message
        if: failure()
        run: |
          echo "YOUR COMMIT IS NOT SECURE!!! FOLLOW THE STEPS BELOW AND REMOVE IT FROM GIT" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "How to Delete Commits in Git" >> $GITHUB_STEP_SUMMARY
          echo "----------------------------" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "You can easily delete commits in git using git reset command. But there are a few things to keep in mind, while working with it, as you can see below." >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Before you run the following commands, it is advisable to use git stash to save all the changes in your present branch." >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Here is the command to delete the previous commit in your existing branch. It will delete the last commit of your present working branch." >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "`$ git reset --hard HEAD~1`" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "The number ~1 indicates that you want to delete the last 1 commit. If you want to delete last 5 commits, replace 1 with 5 above." >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "`$ git reset --hard HEAD~5`" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "The above command will take your HEAD back by 5 commits." >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "If you want to go back to a specific commit, find its commit id using git log command, and then use git reset as follows." >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "`$ git reset --hard <sha1-commit-id>`" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "The above commands will only delete commits locally. What if you want to remove them from the remote origin/branch also where you had pushed these commits earlier. In such cases, use the following command after you have deleted commits locally." >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "`$ git push origin HEAD --force`" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "That’s it. In this short article, we have learnt how to delete commits from git. You can delete commits from any branch including master branch. You need to first switch to that branch, before you run the above commands." >> $GITHUB_STEP_SUMMARY
