name: Scan Secrets
on:
  workflow_call
  
jobs:
  TruffleHog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3        
        with:
          ref: 'develop'
          fetch-depth: 0  
   
      - name: Find first and last commits of Branch
        id: commits
        run: |
          git checkout ${{ github.head_ref }}
          git pull
          git fetch
          echo "::set-output name=last::$(git log  develop..${{ github.head_ref }} --oneline | head -1)"
          echo "::set-output name=first::$(git log  develop..${{ github.head_ref }} --oneline | tail -1)"
         
   
      - name: Validate if current PR can have exposed secrets
        uses: trufflesecurity/trufflehog@v3.4.3
        with:
          path: ./
          base: ${{ steps.commits.outputs.first }}
          head: ${{ steps.commits.outputs.last }}
