name: Scan Secrets
on:
  workflow_call
  
jobs:
  TruffleHog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  
   
      - name: Find first and last commits of Branch
        id: commits
        run: |
          echo "::set-output name=last::git log  develop..bugfix/PD-2778-Sharepoint-Contributions-TimeBomb --oneline | head -1"
          echo "::set-output name=first::git log  develop..bugfix/PD-2778-Sharepoint-Contributions-TimeBomb --oneline | tail -1"
         
   
      - name: Validate if current PR can have exposed secrets
        uses: trufflesecurity/trufflehog@v3.4.3
        with:
          path: ./
          base: ${{ steps.commits.outputs.first }}
          head: ${{ steps.commits.outputs.last }}
